//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorCodeEnumerationWithResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMsg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErrorCodeEnumerationWithResource.ErrorMsg", typeof(ErrorMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been cancelled..
        /// </summary>
        internal static string CanceledRequest {
            get {
                return ResourceManager.GetString("CanceledRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process the request due to connectivity issue with &apos;{IntegratorName}&apos;..
        /// </summary>
        internal static string External_CommunicationError {
            get {
                return ResourceManager.GetString("External_CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been failed..
        /// </summary>
        internal static string External_Declined {
            get {
                return ResourceManager.GetString("External_Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is rejected in fraud detection as suspicious..
        /// </summary>
        internal static string External_DeniedByRisk {
            get {
                return ResourceManager.GetString("External_DeniedByRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process the request due to system misconfiguration..
        /// </summary>
        internal static string External_ExpiredCredentials {
            get {
                return ResourceManager.GetString("External_ExpiredCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been expired..
        /// </summary>
        internal static string External_ExpiredRequest {
            get {
                return ResourceManager.GetString("External_ExpiredRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Message}.
        /// </summary>
        internal static string External_Failure {
            get {
                return ResourceManager.GetString("External_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraud profile is misconfigured..
        /// </summary>
        internal static string External_FraudManagerIsMisconfigured {
            get {
                return ResourceManager.GetString("External_FraudManagerIsMisconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process the request due to unknown error occurred on &apos;{IntegratorName}&apos;..
        /// </summary>
        internal static string External_GeneralFailure {
            get {
                return ResourceManager.GetString("External_GeneralFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process the request due to internal server error occurred on &apos;{IntegratorName}&apos;..
        /// </summary>
        internal static string External_InternalServerError {
            get {
                return ResourceManager.GetString("External_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process the request due to invalid or not supported card..
        /// </summary>
        internal static string External_InvalidCard {
            get {
                return ResourceManager.GetString("External_InvalidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process the request due to system misconfiguration..
        /// </summary>
        internal static string External_InvalidCredentials {
            get {
                return ResourceManager.GetString("External_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process the request due to invalid request data..
        /// </summary>
        internal static string External_InvalidFieldValue {
            get {
                return ResourceManager.GetString("External_InvalidFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{IntegratorName}&apos; could not process the request due to invalid data..
        /// </summary>
        internal static string External_InvalidRequestData {
            get {
                return ResourceManager.GetString("External_InvalidRequestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process the response data..
        /// </summary>
        internal static string External_InvalidResponseData {
            get {
                return ResourceManager.GetString("External_InvalidResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process the request due to system misconfiguration..
        /// </summary>
        internal static string External_Misconfiguration {
            get {
                return ResourceManager.GetString("External_Misconfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process the request due to missing request data..
        /// </summary>
        internal static string External_MissingRequiredField {
            get {
                return ResourceManager.GetString("External_MissingRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process the request due to not supported card type..
        /// </summary>
        internal static string External_NotSupportedCardType {
            get {
                return ResourceManager.GetString("External_NotSupportedCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Message}.
        /// </summary>
        internal static string External_OabFailure {
            get {
                return ResourceManager.GetString("External_OabFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund is not allowed in the current state of the order. Either capture or reverse the remaining amount and try again..
        /// </summary>
        internal static string External_RefundNotAllowed {
            get {
                return ResourceManager.GetString("External_RefundNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process the request due to invalid data..
        /// </summary>
        internal static string External_ResourceNotFound {
            get {
                return ResourceManager.GetString("External_ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process the request due to timeout happened at the External system..
        /// </summary>
        internal static string External_TimeoutOnExternalSystem {
            get {
                return ResourceManager.GetString("External_TimeoutOnExternalSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request data is not valid..
        /// </summary>
        internal static string FailedToDeserializeData {
            get {
                return ResourceManager.GetString("FailedToDeserializeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process the request..
        /// </summary>
        internal static string FailedToProcessRequest {
            get {
                return ResourceManager.GetString("FailedToProcessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is unable to process the request due to some internal system error..
        /// </summary>
        internal static string GeneralIntegratorError {
            get {
                return ResourceManager.GetString("GeneralIntegratorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal system error has occurred..
        /// </summary>
        internal static string InternalSystemError {
            get {
                return ResourceManager.GetString("InternalSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Message}.
        /// </summary>
        internal static string InvalidParameterCombination {
            get {
                return ResourceManager.GetString("InvalidParameterCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {ParameterName} has invalid value..
        /// </summary>
        internal static string InvalidParameterValue {
            get {
                return ResourceManager.GetString("InvalidParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request data is not valid..
        /// </summary>
        internal static string InvalidRequestData {
            get {
                return ResourceManager.GetString("InvalidRequestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {ParameterName} is missing..
        /// </summary>
        internal static string MissingRequiredParameter {
            get {
                return ResourceManager.GetString("MissingRequiredParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API version {Version} is not supported..
        /// </summary>
        internal static string NotSupportedApiVersion {
            get {
                return ResourceManager.GetString("NotSupportedApiVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API version minor {Version} is not supported..
        /// </summary>
        internal static string NotSupportedApiVersionMinor {
            get {
                return ResourceManager.GetString("NotSupportedApiVersionMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported currency..
        /// </summary>
        internal static string NotSupportedIntegratorCurrency {
            get {
                return ResourceManager.GetString("NotSupportedIntegratorCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {ParameterName} has not supported value..
        /// </summary>
        internal static string NotSupportedParameterValue {
            get {
                return ResourceManager.GetString("NotSupportedParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is unable to process the response..
        /// </summary>
        internal static string SystemIsUnableToProcessResponse {
            get {
                return ResourceManager.GetString("SystemIsUnableToProcessResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not process the request due to system misconfiguration..
        /// </summary>
        internal static string SystemMisconfigured {
            get {
                return ResourceManager.GetString("SystemMisconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is rejected due to security violation..
        /// </summary>
        internal static string Zamp_PaymentAmountMismatch {
            get {
                return ResourceManager.GetString("Zamp_PaymentAmountMismatch", resourceCulture);
            }
        }
    }
}
